import {queryGeneric,mutationGeneric,actionGeneric,internalQueryGeneric,internalMutationGeneric,internalActionGeneric} from 'convex/server';
import type {DataModelFromSchemaDefinition,QueryBuilder,MutationBuilder,ActionBuilder,GenericQueryCtx} from 'convex/server';
import type schema from './schema';
export type DataModel=DataModelFromSchemaDefinition<typeof schema>;
export type QueryCtx=GenericQueryCtx<DataModel>;
export const query=queryGeneric as QueryBuilder<DataModel,'public'>;
export const mutation=mutationGeneric as MutationBuilder<DataModel,'public'>;
export const action=actionGeneric as ActionBuilder<DataModel,'public'>;
export const internalQuery=internalQueryGeneric as QueryBuilder<DataModel,'internal'>;
export const internalMutation=internalMutationGeneric as MutationBuilder<DataModel,'internal'>;
export const internalAction=internalActionGeneric as ActionBuilder<DataModel,'internal'>;
