import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { motion, useReducedMotion, animate } from 'motion/react';
import type { HTMLMotionProps } from 'motion/react';
export function PremiumButton({variant='secondary',loading=false,children,...props}:Omit<HTMLMotionProps<'button'>,'children'>&{children?:ReactNode;variant?:'primary'|'secondary'|'success'|'warning'|'danger'|'ghost';loading?:boolean}){const reduced=useReducedMotion();return <motion.button {...props} className={`premium-button ${variant} ${props.className||''}`} disabled={loading||props.disabled} aria-busy={loading} whileTap={reduced?undefined:{scale:.98,y:1}}>{loading?<span className="premium-spinner" aria-label="جارٍ التنفيذ"/>:null}{children}</motion.button>;}
export function AnimatedCard({children,...props}:HTMLMotionProps<'article'>){const reduced=useReducedMotion();return <motion.article {...props} whileHover={reduced?undefined:{y:-3}} transition={{duration:.18}}>{children}</motion.article>;}
export const HoverLiftCard=AnimatedCard;
export function SectionReveal({children,...props}:HTMLMotionProps<'section'>){const reduced=useReducedMotion();return <motion.section {...props} initial={reduced?false:{opacity:0,y:8}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.05}} transition={{duration:.22}}>{children}</motion.section>;}
export function PageTransition({children,...props}:HTMLMotionProps<'main'>){const reduced=useReducedMotion();return <motion.main {...props} initial={reduced?false:{opacity:.6,y:5}} animate={{opacity:1,y:0}} transition={{duration:.18}}>{children}</motion.main>;}
export function AnimatedInput(props:HTMLMotionProps<'input'>){return <motion.input {...props} transition={{duration:.15}}/>;}
export function AnimatedSelect(props:HTMLMotionProps<'select'>){return <motion.select {...props}/>;}
export function AnimatedNumber({value}:{value:string|number}){const ref=useRef<HTMLSpanElement>(null);const reduced=useReducedMotion();const previous=useRef<number>(0);useEffect(()=>{const number=Number(String(value).replaceAll(',',''));if(!Number.isFinite(number)||reduced||ref.current?.closest('.register-print,.voucher-print'))return;const digits=String(value).split('.')[1]?.length||0;const controls=animate(previous.current,number,{duration:.35,onUpdate:n=>{if(ref.current)ref.current.textContent=new Intl.NumberFormat('en-US',{maximumFractionDigits:digits,minimumFractionDigits:digits}).format(n);},onComplete:()=>{if(ref.current)ref.current.textContent=String(value);}});previous.current=number;return ()=>controls.stop();},[value,reduced]);return <span className="premium-number"><span className="sr-only">{value}</span><span ref={ref} aria-hidden="true">{value}</span></span>;}
export function StatusPulse({children,tone='info'}:{children:ReactNode;tone?:string}){return <span className={`premium-status ${tone}`}><i/>{children}</span>;}
export function LoadingShimmer(){return <div className="premium-shimmer" role="status" aria-label="معاينة التحميل"><span/><span/><span/></div>;}
export function LoadingPreview(){const [show,setShow]=useState(false);useEffect(()=>{if(!show)return;const timer=setTimeout(()=>setShow(false),700);return ()=>clearTimeout(timer);},[show]);return <><PremiumButton type="button" onClick={()=>setShow(true)}>معاينة شكل التحميل</PremiumButton>{show&&<LoadingShimmer/>}</>;}
export function PremiumToast({title,description,tone='success',close}:{title:string;description:string;tone?:string;close:()=>void}){const reduced=useReducedMotion();return <motion.aside className={`premium-toast ${tone}`} role="status" initial={{opacity:0,y:reduced?0:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:reduced?0:5}}><span aria-hidden="true">{tone==='success'?'✓':tone==='error'?'!':'ⓘ'}</span><div><b>{title}</b><p>{description}</p></div><button aria-label="إغلاق الإشعار" onClick={close}>×</button></motion.aside>;}
export function AnimatedModal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){const ref=useRef<HTMLDialogElement>(null);const reduced=useReducedMotion();const closing=useRef(false);const exitAnimation=useRef<Animation|null>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>{exitAnimation.current?.cancel();d?.close();};},[]);function dismiss(){if(closing.current)return;closing.current=true;if(reduced){close();return;}const a=ref.current?.animate([{opacity:1,transform:'translateY(0) scale(1)'},{opacity:0,transform:'translateY(5px) scale(.985)'}],{duration:120});if(a){exitAnimation.current=a;a.onfinish=close;}else close();}return <dialog ref={ref} className="tl-modal premium-modal" aria-label={title} onCancel={e=>{e.preventDefault();dismiss();}}><div className="tl-modal-heading"><h2>{title}</h2><PremiumButton type="button" onClick={dismiss}>إغلاق</PremiumButton></div>{children}</dialog>;}
export function AnimatedDrawer(props:HTMLMotionProps<'div'>){const reduced=useReducedMotion();return <motion.div {...props} initial={reduced?false:{x:24,opacity:0}} animate={{x:0,opacity:1}} transition={{duration:.18}}/>;}

export function FinancialValue({value}:{value:ReactNode}){if(typeof value==='number')return <AnimatedNumber value={value}/>;if(typeof value!=='string'||!/^[-\d,.]+(?:\s(?:USD|IQD|EUR|IRT|TRY|Toman))?$/.test(value))return <>{value}</>;const [number,...rest]=value.split(' ');return <><AnimatedNumber value={number}/>{rest.length?' '+rest.join(' '):''}</>;}
