import {useState,useSyncExternalStore} from 'react';
import type {ReactNode,FormEvent} from 'react';
import {isUnlocked,loginLocal,subscribeAccess,accessError,accessVersion} from '../data/localAccess';
import './localAccess.css';
export default function LocalAccess({children}:{children:ReactNode}){
 useSyncExternalStore(subscribeAccess,accessVersion);const unlocked=isUnlocked();const phone='';const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(!await loginLocal(phone,password)){setError('الرقم أو رمز الإدارة غير صحيحة.');return;}setPassword('');}catch{setError('تعذر تسجيل الدخول. تحقق من البيانات والاتصال أو تواصل مع الإدارة.');}finally{setBusy(false);}}
 if(unlocked)return <>{children}</>;
 return <main className="local-login" dir="rtl"><section className="panel local-login-card"><img src={`${import.meta.env.BASE_URL}icon-512.png`} alt="شعار أعمال المستقبل"/><p className="eyebrow">أعمال المستقبل</p><h1>دخول الإدارة</h1><p>لوحة إدارة تجار الصيرفة</p><form onSubmit={submit}><label className="tl-field"><span>رمز الإدارة</span><input aria-label="رمز الإدارة" type="password" autoComplete="current-password" placeholder="أدخل رمز الإدارة" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{(error||accessError())&&<p role="alert" className="tl-error">{error||accessError()}</p>}<button className="tl-button primary" disabled={busy}>{busy?'جارٍ التحقق…':'تسجيل الدخول'}</button></form><a className="login-whatsapp" href="https://wa.me/9647741112113" target="_blank" rel="noopener noreferrer" aria-label="مراسلة الإدارة عبر واتساب"><svg viewBox="0 0 24 24" width="25" height="25" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M20.5 11.5a8.5 8.5 0 0 1-12.7 7.4L3 20.5l1.6-4.8A8.5 8.5 0 1 1 20.5 11.5Z"/><path d="M8 7.5c-.8.4-.9 1.4-.5 2.5 1 2.5 3 4.5 5.5 5.5 1.1.4 2.1.3 2.5-.5l.5-1-2.5-1.2-.8.9a8 8 0 0 1-3-3l.9-.8L9.4 7Z"/></svg><span>مراسلة الإدارة عبر الواتساب</span><span aria-hidden="true">↗</span></a><small>دخول الإدارة محمي بالتحقق من الخادم</small></section></main>;
}
