import {useState} from 'react';
import type {FormEvent} from 'react';
import {changeLocalPassword} from '../data/localAccess';
export default function AdminSettings(){
 const [theme,setTheme]=useState(()=>{try{return localStorage.getItem('almustaqbal-admin-theme')==='light'?'light':'dark';}catch{return document.documentElement.dataset.theme==='light'?'light':'dark';}});
 const [current,setCurrent]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 function appearance(value:string){setTheme(value);document.documentElement.dataset.theme=value;try{localStorage.setItem('almustaqbal-admin-theme',value);}catch{/* Appearance remains available in this tab. */}}
 async function save(event:FormEvent){event.preventDefault();if(busy)return;setError('');setNotice('');if(password.length<8){setError('استخدم كلمة سر من 8 أحرف أو أرقام على الأقل.');return;}if(password!==confirm){setError('تأكيد كلمة السر غير مطابق.');return;}if(password===current){setError('اختر كلمة سر جديدة مختلفة.');return;}setBusy(true);try{await changeLocalPassword(current,password);setCurrent('');setPassword('');setConfirm('');setNotice('تم تغيير كلمة سر الإدارة. احفظها في مكان آمن؛ تم إنهاء صلاحية جلسات الإدارة الأخرى.');}catch(e){const message=e instanceof Error?e.message:'';setError(message.includes('INVALID_CREDENTIALS')?'كلمة السر الحالية غير صحيحة.':message.includes('TOO_MANY_ATTEMPTS')?'محاولات كثيرة. أعد المحاولة بعد 15 دقيقة.':'تعذر تغيير كلمة السر. تحقق من الاتصال والجلسة وأعد المحاولة.');}finally{setBusy(false);}}
 return <div className="admin-settings"><div className="admin-heading"><div><p className="eyebrow">لوحة الإدارة</p><h1>الإعدادات</h1><p>المظهر وكلمة سر دخول الإدارة.</p></div></div><section className="panel"><h2>المظهر</h2><div className="merchant-actions"><button className="tl-button" aria-pressed={theme==='dark'} onClick={()=>appearance('dark')}>ليلي</button><button className="tl-button" aria-pressed={theme==='light'} onClick={()=>appearance('light')}>نهاري</button></div></section><section className="panel"><h2>تغيير كلمة سر النظام</h2><p className="tl-disclaimer">تغيير رمز دخول الأدمن فقط. كلمات سر التجار تبقى كما هي.</p><form className="admin-form" onSubmit={save}>{[{label:'كلمة السر الحالية',value:current,set:setCurrent,auto:'current-password'},{label:'كلمة السر الجديدة',value:password,set:setPassword,auto:'new-password'},{label:'تأكيد كلمة السر',value:confirm,set:setConfirm,auto:'new-password'}].map(field=><label className="tl-field" key={field.label}><span>{field.label}</span><input aria-label={field.label} type="password" autoComplete={field.auto} value={field.value} onChange={e=>field.set(e.target.value)} required maxLength={128} disabled={busy}/></label>)}{error&&<p className="tl-error" role="alert">{error}</p>}{notice&&<p className="tl-notice" role="status">{notice}</p>}<button className="tl-button primary" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ كلمة السر'}</button></form></section></div>;
}
